sudo: false
language: ruby
# Limit ruby versions to currently supported versions to avoid a big build matrix
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.1
# Load database schema before rake
before_script: bundle exec rake db:schema:load
# Test on all supported rails versions
gemfile:
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile
